# -*- coding: utf-8 -*-
# Generated by descriptor builder.  DO NOT EDIT!
# source: circuitrules.proto
"""Generated protocol buffer code."""

from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

import mimiqcircuits.proto.circuit_pb2 as circuit__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12circuitrules.proto\x1a\rcircuit.proto"6\n\tLossModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1b\n\x05rules\x18\x02 \x03(\x0b2\x0c.CircuitRule"\x8c\x01\n\x0bCircuitRule\x12!\n\tdrop_rule\x18\x01 \x01(\x0b2\x0c.DropRuleMsgH\x00\x12)\n\rdecorate_rule\x18\x02 \x01(\x0b2\x10.DecorateRuleMsgH\x00\x12\'\n\x0creplace_rule\x18\x03 \x01(\x0b2\x0f.ReplaceRuleMsgH\x00B\x06\n\x04kind",\n\x0bDropRuleMsg\x12\x1d\n\toperation\x18\x01 \x01(\x0b2\n.Operation"`\n\x0fDecorateRuleMsg\x12\x1d\n\toperation\x18\x01 \x01(\x0b2\n.Operation\x12\x1e\n\ndecoration\x18\x02 \x01(\x0b2\n.Operation\x12\x0e\n\x06before\x18\x03 \x01(\x08"P\n\x0eReplaceRuleMsg\x12\x1d\n\toperation\x18\x01 \x01(\x0b2\n.Operation\x12\x1f\n\x0breplacement\x18\x02 \x01(\x0b2\n.Operationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, __name__, _globals)
# @@protoc_insertion_point(module_scope)
