# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hamiltonian.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 2, "", "hamiltonian.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mimiqcircuits.proto.pauli_pb2 as pauli__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x11hamiltonian.proto\x1a\x0bpauli.proto"S\n\x0fHamiltonianTerm\x12\x13\n\x0b\x63oefficient\x18\x01 \x01(\x01\x12\x1b\n\x05pauli\x18\x02 \x01(\x0b\x32\x0c.PauliString\x12\x0e\n\x06qubits\x18\x03 \x03(\x03".\n\x0bHamiltonian\x12\x1f\n\x05terms\x18\x01 \x03(\x0b\x32\x10.HamiltonianTermb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "hamiltonian_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_HAMILTONIANTERM"]._serialized_start = 34
    _globals["_HAMILTONIANTERM"]._serialized_end = 117
    _globals["_HAMILTONIAN"]._serialized_start = 119
    _globals["_HAMILTONIAN"]._serialized_end = 165
# @@protoc_insertion_point(module_scope)
