# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: optim.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 33, 0, "", "optim.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import mimiqcircuits.proto.circuit_pb2 as circuit__pb2
import mimiqcircuits.proto.qcsresults_pb2 as qcsresults__pb2
import mimiqcircuits.proto.hamiltonian_pb2 as hamiltonian__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0boptim.proto\x1a\rcircuit.proto\x1a\x10qcsresults.proto\x1a\x11hamiltonian.proto"9\n\x12ParametersDictItem\x12\x14\n\x03key\x18\x01 \x01(\x0b\x32\x07.Symbol\x12\r\n\x05value\x18\x02 \x01(\x01"\xa3\x01\n\x16OptimizationExperiment\x12\x19\n\x07\x63ircuit\x18\x01 \x01(\x0b\x32\x08.Circuit\x12\x11\n\toptimizer\x18\x02 \x01(\t\x12\'\n\ninitparams\x18\x03 \x03(\x0b\x32\x13.ParametersDictItem\x12\x10\n\x08maxiters\x18\x04 \x01(\x04\x12\x11\n\tzregister\x18\x05 \x01(\x04\x12\r\n\x05label\x18\x06 \x01(\t"f\n\x0fOptimizationRun\x12\x0c\n\x04\x63ost\x18\x01 \x01(\x01\x12\'\n\nparameters\x18\x02 \x03(\x0b\x32\x13.ParametersDictItem\x12\x1c\n\x07results\x18\x03 \x01(\x0b\x32\x0b.QCSResults"X\n\x13OptimizationResults\x12\x1e\n\x04\x62\x65st\x18\x01 \x01(\x0b\x32\x10.OptimizationRun\x12!\n\x07history\x18\x02 \x03(\x0b\x32\x10.OptimizationRunb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "optim_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PARAMETERSDICTITEM"]._serialized_start = 67
    _globals["_PARAMETERSDICTITEM"]._serialized_end = 124
    _globals["_OPTIMIZATIONEXPERIMENT"]._serialized_start = 127
    _globals["_OPTIMIZATIONEXPERIMENT"]._serialized_end = 290
    _globals["_OPTIMIZATIONRUN"]._serialized_start = 292
    _globals["_OPTIMIZATIONRUN"]._serialized_end = 394
    _globals["_OPTIMIZATIONRESULTS"]._serialized_start = 396
    _globals["_OPTIMIZATIONRESULTS"]._serialized_end = 484
# @@protoc_insertion_point(module_scope)
