name: Test

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - devel

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Checkoout private deps
        if: github.repository == 'qperfect-io/mimiqcircuits-python-private'
        uses: actions/checkout@v3
        with:
          repository: qperfect-io/mimiqlink-python
          token: ${{secrets.GH_PAT }}
          path: mimiqlink-python

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add private dependencies
        if: github.repository == 'qperfect-io/mimiqcircuits-python-private'
        run: |
          uv add 'mimiqlink @ ./mimiqlink-python'

      - name: Install dependencies
        run: |
          uv sync --all-extras

      - name: Run tests
        run: |
          uv run pytest -sxv